fix:the log is archived into the wrong file
arthurkiller/rollingwriter pull request #29
Opened 2020-09-09 03:48 UTC by dequanLi

当长时间没有日志写入的时候，后续的前几条日志易被归档到错误的文件中。
针对上诉问题，做了一下修复。同时，配置文件中新增了FilterEmptyBackup参数，来控制是否需要对空的文件进行备份操作。

2020-09-09 05:54 UTC, arthurkiller commented on writer.go
> +DoWrite:
能否不要 goto 呢？

2020-09-09 05:55 UTC, arthurkiller requested changes

2020-09-09 05:55 UTC, arthurkiller commented on writer.go
> +		goto DoWrite
能否不要 goto 呢？

2020-09-09 05:55 UTC, arthurkiller commented on writer.go
> +			goto DoWrite
same

2020-09-09 05:55 UTC, arthurkiller commented on writer.go
> +DoWrite:
same

2020-09-09 06:20 UTC, dequanLi commented on writer.go
> +DoWrite:
好的，我尝试一下，看看怎么不使用goto来解决哈

2020-09-10 03:07 UTC, dequanLi commented on writer.go
> +DoWrite:
hi，关于监听 备份的chan，之前有没有考虑过，通过一个goroutine来搞呢？如下：
```
// Watch listen reopen chan
func (w *Writer) Watch() {
	if w.cf.RollingPolicy == WithoutRolling {
		return
	}

	go func() {
		for {
			select {
			case filename := <-w.fire:
				if err := w.Reopen(filename); err != nil {
					w.reOpenErr <- err
				}
			}
		}
	}()
}
```
写操作如下：
```
func (w *LockedWriter) Write(b []byte) (n int, err error) {
	w.Lock()

	select {
	case err := <-w.reOpenErr:// 监听备份失败
		return 0, err
	default:
	}
	n, err = w.file.Write(b)
	w.Unlock()
	return
}
```
如果采用这种方式，可以不使用 goto，但是可能会引发另外一个问题：
因没加锁，当`defer (*os.File)(oldfile).Close()`的时候，正好有一个协程在处理 ` w.file.Write(b) `,可能会导致写失败。
你这边有没有什么建议呢？

2020-09-13 04:00 UTC, arthurkiller commented on writer.go
> +DoWrite:
我是说不需要 goto，语句都是相等的吧？

```
var ok bool = false
for !ok {
	select {
	case filename := <-w.fire:
		if err := w.Reopen(filename); err != nil {
			return 0, err
		}
	default:
        ok = true
	}
}

```

2020-09-14 02:49 UTC, dequanLi commented on writer.go
> +DoWrite:
赞，当时理解错了，已经提交

2020-09-14 04:02 UTC, arthurkiller requested changes

2020-09-14 04:02 UTC, arthurkiller commented on writer.go
> +		var ok = false
能否优化一下代码逻辑把 `w.fire` 和 `w.errChan`放在一个 select 中处理？

2020-09-14 09:51 UTC, dequanLi commented on writer.go
> +		var ok = false
好的，已fix

2020-09-14 10:08 UTC, arthurkiller requested changes

2020-09-14 10:08 UTC, arthurkiller commented on writer.go
> +	for ! ok {
为啥要判断 ok ？

2020-09-15 02:30 UTC, dequanLi commented on writer.go
> +	for ! ok {
![image](https://user-images.githubusercontent.com/25575950/93158096-1294dc00-f73e-11ea-80fd-c89773c3d579.png)
如果不判断，不是没法跳出for循环吗？

2020-09-15 03:54 UTC, arthurkiller commented on writer.go
> +	for ! ok {
我的意思是，这里不需要 for

1. 如果没有 fire ，那么就可以直接写
2. 如果 fire 了，那么久 reopen，然后再写

2020-09-15 05:25 UTC, dequanLi commented on writer.go
> +	for ! ok {
大佬，我觉得可能存在这种情况
有 fire ，且存在一个或多个Goroutine，因为要写fire而被阻塞。

针对这种情况，若不采用for的话，可能存在连续几次的Write，每次都会触发reOpen，这样就被归档到不同的文件。
本质上，连续的几次Write可能是要放同一个文件。

你觉得呢？

2020-09-15 06:58 UTC, arthurkiller commented on writer.go
> +	for ! ok {
> 针对这种情况，若不采用for的话，可能存在连续几次的Write，每次都会触发reOpen，这样就被归档到不同的文件。

这种 case 没太理解

2020-09-15 07:12 UTC, dequanLi commented on writer.go
> +	for ! ok {
我描述一下这种case哈
针对 TimeRolling 类型的日志
![image](https://user-images.githubusercontent.com/25575950/93177114-df197800-f764-11ea-8c63-7fe721fbc9ac.png)
每间隔一段时间，就往fire中插入数据。

假设0点~10点时间段内，没有日志写入，且设置的，每隔1小时 归档一次。

于是就存在10个goruntine阻塞在写chan的地方
```
m.fire <- m.GenLogFileName(c)
```

在写日志的地方，如果我们不使用for循环

在11点的时候，前10次写操作，都会触发Reopen

这样同一个时间段的时候，被归档到不同的文件中。

2020-09-16 03:35 UTC, arthurkiller commented on writer.go
> +	for ! ok {
嗯，明白了，所以修复方式应在你截图这里
```golang
select {
    case m.fire <- m.genlogfilename():
    default: 
}
```

2020-09-16 03:35 UTC, arthurkiller commented on writer.go
> +	for ! ok {
如果写不进去，就不用写，说明上一次切分还未进行。

2020-09-16 05:40 UTC, dequanLi commented on writer.go
> +	for ! ok {
是呢，可以修改截图的地方
但是改为下面的方式会有问题
```
select {
    case m.fire <- m.genlogfilename():
    default: 
}
```
因为写chan的时候，可能并不能保证一定有写日志，容易导致`m.genlogfilename()`没法写入m.fire。

然后，下次写日志的时候，`m.fire`仍然是空的，所以也不会触发切片操作，但是此时应该触发切片。

之前想过，通过`time.After`来搞，但是`After`里面参数时间填写多久，不好控制，理想时间是，一个切片周期。
```
select {
	case m.fire <- m.genlogfilename():
	case <- time.After(time.Second):
	}
```

2020-09-16 06:09 UTC, dequanLi commented on writer.go
> +	for ! ok {
此外，如果我们直接从截图的地方来修改，还有一个问题，就是会忽略针对空文件的切片

2020-09-16 06:11 UTC, dequanLi commented on writer.go
> +	for ! ok {
此外，如果我们直接从截图的地方来修改，还有一个问题，就是会忽略针对空文件的切片。

在 `write`地方修改，我们可以通过配置`FilterEmptyBackup`参数，来控制是否忽略，空文件的切片

![image](https://user-images.githubusercontent.com/25575950/93298786-7397df00-f826-11ea-94bf-5f767cf503ca.png)

2020-09-21 06:12 UTC, dequanLi commented on writer.go
> +	for ! ok {
大佬，有结果了吗？

2020-09-23 11:09 UTC, arthurkiller commented on writer.go
> +	for ! ok {
merged

2020-09-23 11:10 UTC, arthurkiller commented on writer.go
> +	for ! ok {
先 merge 吧，看下修复下冲突？

2020-09-23 12:07 UTC, arthurkiller approved these changes

2020-09-24 11:33 UTC, dequanLi commented on writer.go
> +	for ! ok {
已fix

2020-09-24 12:09 UTC, merged

2020-09-24 12:09 UTC, arthurkiller commented
@dequanLi 合并了哈，thx